cacheFolder: ./.yarn/cache

compressionLevel: mixed

defaultLanguageName: node

enableColors: true

enableGlobalCache: false

enableHyperlinks: true

enableInlineBuilds: true

enableProgressBars: true

enableStrictSsl: false

logFilters:
  - code: YN0000
    level: info
  - code: YN0007
    level: info
  - code: YN0013
    level: info
  - code: YN0032
    level: info
  - code: YN0060
    level: info
  - code: YN0061
    level: info

nmHoistingLimits: workspaces

nmSelfReferences: true

nodeLinker: node-modules

npmAlwaysAuth: false

npmRegistryServer: "https://registry.npmjs.org/"

pnpFallbackMode: all

pnpMode: strict

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
